version: '2'
services:
    adminbo-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/adminBo/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=adminBo
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
