version: '2'
services:
    statistic-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/statistic/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=statistic
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
