version: '2'
services:
    homebo-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/homeBo/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=homeBo
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
